2.1.2.4-8/28-任务书更新翻译和校对
Kiwi233/Translation-of-GTNH pull request #235
Opened 2022-08-30 17:44 UTC by ChromicRedBrick

2022-09-03 04:59 UTC, Kiwi233 requested changes
test

2022-09-03 04:59 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2.desc=你真幸运!这本书有内置的阅读灯光. 这样你就能在漫漫长夜里静静阅读,但现在你还需要完成一些基础工作. 要是天还没有黑下来,出去收集一些沙砾和木材吧. 记住,你需要食物. 去寻找潘马斯的菜园(记得留下种子!).%n%n§3要是你还没去看,请确保在可以的时候认真阅读第一个任务引出的信息任务,它们非常重要!
这里是在避难所等待黑夜结束，所以不是“天还没黑下来”

2022-09-03 04:59 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1305.desc=ME流体接口在合成时也会发送流体.你可以用桶、单元、大型单元甚至是容量瓶在样板配方中写入流体.它会发送配方指定量的流体.%n%n如果要发送给组装机一类可以同时接收流体和物品的GT机器,请使用面板模式.如果你想在多方块机器上使用它,就比较复杂了.你可以使用面板模式并且用一个机器外壳来缓存并提取物品和流体,或者你可以使用方块形式的接口,让其正面将物品输出到箱子
ME流体接口在合成时也会发送流体.你可以用桶、单元、大型单元甚至是容量瓶在样板配方中写入流体.它会发送配方指定量的流体.%n%n如果要发送给组装机这类可以同时接收流体和物品的GT机器,请使用面板模式.如果你想将其用于多方块机器,那就比较复杂了.你可以使用面板模式,并用一个机器外壳来缓存/提取物品和流体,或者你可以使用方块形式的接口,让其正面将物品输出到箱子或者输入总线中,其他面发送流体.如果配方中使用了超过一种流体,它会先发送全部流体,再发送物品.如果需要自动化合成工作台配方,请使用ME流体装配室.%n%n译者注:流体相关的配方也可以使用AE2FC(AE2流体合成)来完成,请查找相应的任务.

2022-09-03 04:59 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1315.desc=合成处理单元的组成部分,可以提供1024字节的存储空间.%n%n合成存储器是合成处理单元中唯一不可缺少的组件.每一个合成处理单元都可以完成独立的合成工作(而不是同一个合成工作的子任务).合成工作所需的所有配方需要的物品越多,你就需要越多的合成存储器.使用一个大容量合成存储器配上一堆小容量的可能是个不错的主意,但要记得当你下单合成时,系统会尝试优先使用最大的
合成工作所需的所有配方需要的物品越多,你就需要越多的合成存储器.---->合成工作包含的所有配方所需的物品越多,你就需要越多的合成存储器.

一个合成处理单元不论有多大,都只要一个频道.一个合成处理单元多方块结构不论有多大,都只需要1个频道.
重复

2022-09-03 04:59 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1328.desc=这是一个特殊的用于编码空白样板的ME合成终端.%n%nME样板终端和普通终端一样都可以对网络内的物品进行浏览和管理,但还包含了设计样板的区域.有两种样板编码模式:合成样板和处理样板.处理样板用于不使用标准合成台配方的机器,例如熔炉和其他(几乎所有)mod的机器.点击界面右侧的熔炉/工作台按钮可以切换编码模式:工作台是合成样板模式,熔炉是处理样板模式.%n%
处理样板用于不使用标准合成台配方的机器
这里标准合成台改为标准工作台，感觉会更好一些，包括后面的那些合成台总感觉不标准

工作台是合成样板模式,熔炉是处理样板模式.---->工作台图标代表着合成样板模式,而熔炉图标则代表处理样板模式.

2022-09-03 04:59 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest213.desc=IV级.你的机器将会需要钨钢. 你应该造访火星和它的卫星:火卫一和火卫二.%n%n记得将你的工业高炉线圈升级为钨钢线圈.%n%n到目前为止你应该已经精通了格雷科技,前提是如果你还没有清理过格雷机器在你家里留下的大坑...%n%nGT++多方块结构在这个阶段开始陆续解锁.记得先做一台合金冶炼炉,GT++的绝大部分合金都可用它制作.
IV级.你的机器将会需要钨钢.--->在IV阶段,你的机器将会需要钨钢.

2022-09-03 04:59 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest215.desc=小行星上有些好东西--尤其是硅岩,因此你该顺路去看看.
这里任务书删掉了好多描述，其实可以酌情保留部分正确的

2022-09-03 04:59 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest309.desc=今天早上,你只想往死里打自己的脸.在你过去的旅程中,你已经见过了许多不同颜色的神奇的碎片.但是和你每天使用的那些元始要素的碎片不同,这两种碎片似乎包含了它们所在世界的原始本质.天堂和地狱....两个截然相反的世界.%n%n你认为可以用它们来制造一些...强力的东西.%n%n§3PS： 对,我知道合成时不会消耗珍珠,不过接受这个故事设定,好吗?
这里指的并不是元始，而是六种基础要素碎片

2022-09-04 14:53 UTC, Kiwi233 requested changes

2022-09-04 14:53 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest360.desc=荒凉蜂.也许你能知道事情会如何发展?
这里的 Maybe you can see where this is going?
this应该指的是荒凉蜂，或是这条杂交路线，建议改成
也许你能看到这条杂交路线通向何方?

2022-09-04 14:53 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest358.desc=一只硅岩蜂.它不能让你免做硅岩处理线,但如果你科技足够的话,可以用它的蜂巢来做个诱变机!
这里是蜂窝

2022-09-04 14:53 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest371.desc=实话说,不是很强.
说实话
似乎更通顺一些

2022-09-04 14:53 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest388.desc=你反反复复摆弄了很久,试图将魔法和科技结合起来.看来你终于找到了方法!你将你神秘使和血魔法师的力量和UHV科技相结合,找到了一种将龙的力量精炼成一个小核心的方式.你确信这台机器就可以做这件事--只要你知道如何准确地组装这个核心.%n%n%n§3使用多方块机器全息投影仪了解其搭建方式.你也可以升级龙芯,不过这需要更高等级的蓝图,同时还得升级多方块机器.
你将你神秘使和血魔法师的力量和UHV科技相结合
这里可以省略一个 你

2022-09-04 14:53 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest464.desc=好,这张蓝图是完美的!不管属于何种外星文明,它正是你所需要的.来做个龙芯吧.%n%n%n§3你可以在冥王星地牢中找到蓝图.
Schematic和Blueprint需要区分一下
前者一般为设计图、图纸；后者为蓝图
EMT语言文件中已译为 龙芯图纸，请统一

2022-09-04 14:53 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest536.desc=让我们来做一个板模具,以制作橡胶片.你可以用它们制作线缆,也用于传送带、搋子和其他更多的配方.
这里需要确认一下是模头还是模具

2022-09-04 17:58 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest536.desc=让我们来做一个板模具,以制作橡胶片.你可以用它们制作线缆,也用于传送带、搋子和其他更多的配方.
mold是模具
![image](https://user-images.githubusercontent.com/85604068/188327117-818364b2-4a4d-467e-a73b-dd52e46755e7.png)

2022-09-04 18:01 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest371.desc=实话说,不是很强.
我平常比较习惯用实话说

2022-09-05 17:43 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest536.desc=让我们来做一个板模具,以制作橡胶片.你可以用它们制作线缆,也用于传送带、搋子和其他更多的配方.
确认是模具无误
![image](https://user-images.githubusercontent.com/85604068/188496697-514d5f22-d2ec-4e50-a4e4-b4ed4fdd912e.png)

2022-09-10 14:43 UTC, Kiwi233 requested changes

2022-09-10 14:43 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1351.desc=随着你不断进步,你注意到你的黑色护目镜与又白又亮的完美盔甲不相符. 你决定做一个白色的.
随着科技的不断进步,你注意到原有的黑色护目镜与现在又白又亮的漂亮盔甲不太搭.

2022-09-10 14:43 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1404.desc=无损的MV超导导线怎么样？六氧化五镉镁(MV超导)是一种超导材料,可以毫无损失地传递能量. 现在,每个电压都有超导导线和粗胚导线,超导线损为0而超导粗胚线损很小.%n%n在搅拌机中搅拌镉,镁和氧. 制得的粗胚粉需要用带有坎塔尔合金线圈的工业高炉(EBF)烧制. 再用真空冷冻机来冷却它. 制作一些MV超导粗胚导线并使用组装机将这些导线与氦、不锈钢流体管道和M
这里其实是故意保留长长的材料名，原文里也没有断词，是否需要翻出来还有待商榷，下同

2022-09-10 14:43 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1418.desc=...在我的梦里. 要是我们可以将所有发电机组集中在一个位置,而不是在每个发电机前面放一堆电池,该多好啊？ 把它们放在基地里远离活动范围的部分？ 放在家外乡下的某处？ 让动物面对污染去吧. 无论如何,来着手搭建能源站吧,它可以存储EU并供给我们的基地.
而不是在每个发电机前面放一堆电池
感觉这个前面好像有点奇怪，建议改成
而不是在每台发电机上连(装)一堆电池

另外目前由于兰波顿电容库的增强，以及能源站的削弱，似乎可以加个译注提一下

2022-09-10 14:43 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1475.desc=什么？ 你注意到有时当你杀死怪物,甚至只是牛或鸡,它就爆炸了!这太疯狂了! 要阻止它,请使用合适的GT小刀或GT屠刀来完成最后一击. 用木棍和燧石制作一柄燧石小刀(在NEI上有些难找.花点时间吧),当你的小刀磨损后,我会给你一个铁的.
你注意到有时当你杀死怪物
这里可以补个 “时”

2022-09-11 01:52 UTC, Kiwi233 requested changes

2022-09-11 01:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1404.desc=无损的MV超导导线怎么样？六氧化五镉镁(MV超导)是一种超导材料,可以毫无损失地传递能量. 现在,每个电压都有线损为0的超导导线.%n%n在搅拌机中搅拌镉,镁和氧. 制得的粗胚粉需要用带有坎塔尔合金线圈的工业高炉(EBF)烧制. 再用真空冷冻机来冷却它. 制作一些MV超导粗胚导线并使用组装机将这些导线与氦、不锈钢流体管道和MV泵组合在一起,以获得128EU
这里原文没有问题，修改需要回滚

2022-09-11 12:52 UTC, Kiwi233 requested changes

2022-09-11 12:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1505.desc=更像Too-Many-Items(TMI)了! 以下是使用NEI的一些提示.%n%n当你打开物品栏时,可以在底部文本栏中输入搜索词. 请确保你的GUI大小设置正确,否则你将无法看到它. 双击该栏以突出显示背包及正在查看容器中的所有匹配物品.这在搜索黑曜石箱子,或者找某种看起来完全一样的矿石时非常有用!%n%n更妙的是,你可以使用T搜索附近的容器(键位可以自
最后一句可以去掉 查看终极合成台配方
现在NEI已经做了视图兼容

2022-09-11 12:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1864.desc=资深玩家可能会惊讶,为什么在NEI查匠魂的苔藓球,看不到需要的合成材料.%n%n在这个整合包中,你得先研究神秘时代,才能制造苔藓球.去成为一名危险的神秘使吧,你将获得制造苔藓球的力量,可以使你的工具自动修复自己. 当然,在开始制造前,你需要先到暮色森林收集材料,还得准备铝锭.  苔藓球在魔导手册的GTNH栏,需要注魔.%n%n喝杯啤酒,为你的长途旅行做好准
咳咳 这里有几句漏掉了吧

2022-09-11 12:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2047.desc=有的机器有超多配方.为了避免冲突,一些配方加入了编程电路.%n%n想要使用编程电路,有很多方法:%n%n1)现在所有的单方块GT机器GUI右下角都有一个图标,代表了"虚拟电路板".shift+左击,或是使用滚轮可以选择你需要的电路编号.但是多方块机器没有虚拟电路板.(译者注:现在输入总线也有虚拟电路板了.)%n%n你也可以将LV电路板放入合成格,得到编程电
这里的 合成格 比较统一的叫法为 合成栏

2022-09-11 12:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2089.desc=如果你想要终极的蜜蜂生产速度,工业蜂箱是唯一的道路.  工业蜂箱中类似框架的升级是不会损坏的. 产量升级可以叠加最多8个.还有许多环境模拟类的升级、基因寿命类升级、授粉升级、还有最关键的自动化升级-工业化量产的关键.%n%n现在工业蜂箱是GT机器.它最高可以接受UV电压,最大4A电流,但是基础功率只有37EU/t.你不再需要世界加速器了,并且只有一个电压等
你不再需要世界加速器了,并且只有一个电压等级的机器,所以也不存在超频.
建议改成
你不再需要世界加速器了,并且工业蜂箱只有一个电压等级,所以也不存在超频.

你会想用它们的,它们大幅提升了速度--同时还有能量消耗.
建议改成
你会用得上它们的,它们可以大幅提升速度--同时也会大幅增加能耗.

2022-09-11 12:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2093.desc=电刺激器,一块能加装4个电子管的的电子板,提供多种功能.  表中所有数据均为当前数据%n%n铁电子管-产量:150(最高500)%n钻石电子管-产量:250(最高1000)%n磷灰石电子管-授粉:150(最高500)%n黑曜石电子管-寿命:80(最小20)%n青金石电子管-寿命:150(最高500)%n烈焰电子管-模拟地狱般的温度%n金电子管-突变:150
烈焰电子管这里，可以括号注一下，需要提一下下界

这些刺激也会造成基因衰退几率提高50％
这里 造成 可以换成 导致

2022-09-11 12:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2566.desc=生物实验室是一个多用途生物工程站. 你可以通过它来制造细菌培养皿(用于细菌培养缸),也可以制造DNA样品瓶和数据球,还有质粒样品瓶用于复制细菌.%n%n培养皿之后会在"多方块结构"任务栏中的"细菌培养缸"中用到.如果你有工业化酿造的需求,也可以现在就用;或是等后期需要研究生物工程时使用.%n%n§3如果你只在后期做了细菌培养缸的话,大概也会做一个更高级的生
最后一句
原文大意是
你只需要任意等级的生物实验室即可完成此任务.

2022-09-11 12:52 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2584.desc=这,就是最高级的GT++材料.它需要UMV电压才能加工.所以现在你只能用GT++的大型加工厂固化它.%n%n§3只要拿到了第一块锭,就可以用DTPF制取更多了.我想那个配方应该比用MK4核聚变好多了.%n%n这块蛋糕就是对你走到这一步的奖励.
DTPF指的多方块需要写明，括号注缩写

2022-09-11 14:13 UTC, Kiwi233 requested changes

2022-09-11 14:13 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3217.desc=以宇宙自身的野蛮之力熔炼.%n%n提供11701K的基础炉温.可以用来升级工业高炉,不过我猜用在巨型工业高炉或是DTPF上更好.
宇宙自身的伟力
注意缩写的使用，大部分玩家无法分辨英文缩写所指

2022-09-13 17:40 UTC, Kiwi233 requested changes

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3223.desc=既然有活石了,就开始制造第一座魔力池吧.用锯子将活石切成台阶制作底部,用活石板将它们粘在一起制成四边.%n%n你缺乏使其变得有效的知识,所以很遗憾,你没法合成很多.
把活石板粘在一起制成四边

你无法解锁太多相关合成表

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3225.desc=有些花到处都有,有些则仅限于特定的生物群落.如果你不想离家走太远,可以找些帮手.%n%n具有采蜜对象特性的蜜蜂会在它的工作范围内慢慢产生新的花卉,包括大量从遥远的牧场带来的.
生物群系请统一

最后一句建议改为
包括大量从遥远牧场带来的品种

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3226.desc=魔力钻石是注入了魔力的钻石,制作它们需要的魔力取决于钻石的质量.%n%n一座全满的稀释魔力池勉强能把一颗精致的钻石转变成魔力钻石.只要你升级了魔力池,就可以用普通钻石了,不过魔力消耗会多些.
等到你升级一次魔力池之后

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3227.desc=下一步就是做催化器了.炼金催化器可以使用魔力,将物品或方块转变成相关的另一种物品或方块.%n%n把它放在充满的魔力池下面,做些海晶石试试.
咳咳，最后一句漏了

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3228.desc=你可以用符文祭坛制作符文,符文可以让你获得更高级的花卉.要使用祭坛,把材料放在上面，用森林魔杖右键祭坛,满足条件后,在祭坛上丢一颗活石以完成制作.你还需要一个魔力源,比如一个指向祭坛的魔力发射器.
符文可以让你能够制作更高级的花卉

要使用祭坛xxxx
建议倒过来更符合中文习惯，另外逗号好像有点不统一

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3235.desc=这些全新的仓室让你能从任何维度的任何位置无线发送、存储、接收能量.它们可以放置在任何现有的多方块结构中,和正常的能源仓/动力仓作用相同.无线动力仓会消耗EU,并将其存储在一个与玩家绑定的全局无线网络中.这个无线网络可以存储2^(2^31)EU,远远超过了甚至是最高等级的激光仓.%n%n只要用/gt global_energy_join 玩家1 玩家2指令,
这也是为了也极大降低游戏延迟做的设计
它们是为了尽量降低游戏延迟而设计的

这也可以从庞大的导线网络中节省下一些TPS延迟
这样你就无需搭建庞大的导线网络,从而节省下一些TPS延迟

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3240.desc=现实本身也屈从于你的意志.
现实屈服于你的意志

2022-09-13 17:40 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest3243.desc=干得好.你已经能制作游戏中最高级别的部件了.
你已经触碰到(到达)游戏中可合成的最高部分了

2022-09-15 10:30 UTC, Kiwi233 requested changes

2022-09-15 10:30 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1504.desc=寻矿魔杖减轻了寻找矿石过程中的一些枯燥乏味. 你需要先找到一个矿石放入其中,然后,你就可以用它寻找更多的同种矿石. 它只会告诉你特定矿石是否在附近. 然后你得带着更好的挖掘工具回来并检查每个地点.%n%n确保先用NEI找出哪种矿石是你目前最需要的. 其他基础矿石可以用硬币购买.%n%n使用方式:对着地面Shift+右键以打开库存并将矿石放入槽中. 它的搜索
减轻了。。。一些枯燥乏味
总感觉怪怪的，建议改成使用寻矿魔杖寻找矿石不那么枯燥乏味

2022-09-15 10:30 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1526.desc=充能合金是一种令人惊叹的材料. 它重量轻,硬度高,非常适合制作弩臂. 它的拉弓速度稍慢,但仍然具有惊人的停止力和极高的弩箭速度. 与碳弩臂相比,耐久大幅度提高. 这种材料也可以制成出色的弩箭杆.也许你能找到合适的箭头？
stopping power
在百科被译为停止作用
止动性算是非正式叫法吧

2022-09-15 10:30 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1552.desc=如果你想从货物管理器中装载或卸载许多不同的物品,管道可能会变得非常混乱. 你可以将外部分配器放置在货物管理器旁边,它将帮助你访问货物管理器,可在分配器GUI中指定的不同栏位.非常方便抽出物品!
最后一句倒过来似乎更通顺

2022-09-15 10:30 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1553.desc=既然有了个货物管理器,只要一个特定的铁路,矿车就可以与之互动. 只需将高级探测轨道放在货物管理器旁边,根据其所在侧面的颜色,你必须调整货物管理器GUI中的设置.
有了货物管理器之后,还需要一个特定的轨道,矿车就可以与之交互.

2022-09-15 10:30 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1644.desc=整合包太简单了吗？厌倦了这些枯燥的任务？在Github上发帖狂喷那些菜鸡把蒸汽弄得过强了吗？那么这就是你要把所有这些OP硬币变成盐的任务.
咳咳 语气有些激烈了。。。

2022-09-15 11:39 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1526.desc=充能合金是一种令人惊叹的材料. 它重量轻,硬度高,非常适合制作弩臂. 它的拉弓速度稍慢,但仍然具有惊人的停止力和极高的弩箭速度. 与碳弩臂相比,耐久大幅度提高. 这种材料也可以制成出色的弩箭杆.也许你能找到合适的箭头？
还是用了正式一些的说法

2022-09-15 13:00 UTC, Kiwi233 requested changes

2022-09-15 13:00 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1748.desc=算术逻辑电路用于许多部件合成;往往要按8-16个以至于64个成组使用.%n%n所以请确保供应充足.
以至于--->甚至

2022-09-15 17:07 UTC, Kiwi233 requested changes

2022-09-15 17:07 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1560.desc=要获得巫术种子,你需要在远离水的草地上使用锄头.要打开剩余的任务线,你需要完成神秘时代的任务、研究魔导手册中巫术章节的条目.%n%n传说,当曼德拉草的根被挖出来时,它会尖叫并杀死所有听到它的人.这种说法只是部分正确.一个完全成长的曼德拉草可能会尖叫,给周围的人带来巨大的不适.这就是为什么最好在晚上收获曼德拉草根的原因,那时植物更可能处于休眠状态. 曼德拉草
咳咳 这个还是得统一 水洋蓟吧

2022-09-15 17:07 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1752.desc=如此可控! 奇怪的是,这种部件要用HV电路板制作;所以这儿提供了一些,你可以用MV电路板代替HV电路板兑换,用于制作你的第一台电脑零件.不要把它们全部放在一个地方!
用于制作你的第一台电脑零件
这个 的 挪到后面会好一点，中心词是零件

2022-09-15 17:07 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
>  // +++ // "Allow fluids to be placed first"需要统一译名.
优先发送流体

2022-09-15 17:18 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest75.desc=有限的水源是一个问题,但不要害怕.我会引导你如何拥有稳定的水源. RC的多方块集水器可以保证前期的供水.%n%n生物群系的湿度非常重要,关系到集水器的产水速度.下雨的时候,集水器将被更快地填满.确保有一格集水器露天以获得最快的产水速度.%n%n最妙的是你不需要泵来抽出其中的水.将集水器与管道或储罐相邻放置,集水器就会自动输出水.%n%n§3需要露天以获得最大产
集水器，mod的语言文件也要同步修改

2022-09-15 17:20 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest75.desc=有限的水源是一个问题,但不要害怕.我会引导你如何拥有稳定的水源. RC的多方块集水器可以保证前期的供水.%n%n生物群系的湿度非常重要,关系到集水器的产水速度.下雨的时候,集水器将被更快地填满.确保有一格集水器露天以获得最快的产水速度.%n%n最妙的是你不需要泵来抽出其中的水.将集水器与管道或储罐相邻放置,集水器就会自动输出水.%n%n§3需要露天以获得最大产
那边已经交另一个pr了

2022-09-15 17:21 UTC, Kiwi233 requested changes

2022-09-15 17:21 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1146.desc=也许你在想为什么现在的管道不会自动连接了？这是为了让管道更加的聪明. 现在在安装管道之后,你可以使用扳手来手动连接你想要的管道.你不再需要使用板或者箔来防止管道之间的连接了.%n%n输送温度超过一定值的流体(比如蒸汽)的管道,会对触碰它的玩家造成伤害. 所以你还是得用覆盖板把炽热的管道包住,防止自己走在上头的时候被烫伤! 另外,如果输送的流体温度超过了管道
这里指的不是木制的集水器

2022-09-15 17:21 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest1520.desc=512桶还无法满足你？ 大型铝流体单元每个可容纳32桶流体,最大堆叠64. 一格能装32*64桶液体？ 那可是半个超级缸I!%n%n如果你想装水,RC的集水器无法兼容太大的单元(一次只能装一点点),试着把水转移到GT或GT++的流体容器(如超低压流体储罐或超级缸),然后再装单元. 你至少需要满足单元容量的流体或能容纳单元容量的空间,才能装满单元或倒空它,对
这里也不是

2022-09-15 17:59 UTC, merged