2.2.0.0-9/27任务书校对
Kiwi233/Translation-of-GTNH pull request #262
Opened 2022-09-28 10:25 UTC by ChromicRedBrick

进度：2030/3251

2022-09-30 11:40 UTC, starxingchenc requested changes

2022-09-30 11:40 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2118.desc=龙背包给予你火焰保护、力量、夜视和生命回复效果.%n%n§3它的功能的确很强大,但它也会消耗一个龙蛋,所以请确定这是你必须的,或者你有把握再做个龙蛋.
所以请确定这是你必须的 - > 所以请确定你需要这么做
so be sure you want it

2022-09-30 11:40 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
>  gtnh.quest2121.desc=GT的剪枝器比林业的好多了.根据你所用的材料,它的耐久不同,但远高于林业剪枝器.
根据你所用的材料,它的耐久不同,但远高于林业剪枝器 -> 根据你所用的材料,它可以具有远高于林业剪枝器的耐久
It can have much higher durability based upon which material you use to create it.

2022-09-30 11:40 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2136.desc=能量接收器是向AE网络注入能量的一种可选设备.你可以构建一个只有能源接收器的"哑的"网络,但想要有真正的功能,你还是需要ME控制器.%n%n§3如果要构建子网络,直接用石英纤维传输能量就行了.%n%n译者注:能量接收器可以单独用于构建子网络,但只能提供8个频道.
AE -> AE2
也许需要统一一下？

2022-09-30 11:40 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2137.desc=AE网络的核心.向它注入能量就可以给你的整个网络供能.
未翻译

2022-09-30 11:40 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
>  gtnh.quest2139.desc=虽然猪背包本身没啥用,但它可以转化成非常有用的工具,通过一些正确的...刺激...
刺激  -> 诱因？
motivation

2022-09-30 11:40 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2140.desc=只有最疯狂的傻瓜才会用钻石制作工具! 也许这个疯子大智若愚?%n%n§3PS：你还可以把它们§o用作燃料§r,§3这太疯狂了!
也许它在装疯卖傻
Or is it crazy like a fox?

2022-09-30 11:40 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2144.desc=如果你想让多A电流通过超净间墙壁,使用线缆二极管吧.  当从主电源线分支到通常不会使用那么多A电流的支线时,也可以使用线缆二级管,来很方便地限制电流,除此之外也可防止电流过大着火.
中文语境下似乎使用汉字“安”更好

2022-09-30 15:09 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
>  gtnh.quest2139.desc=虽然猪背包本身没啥用,但它可以转化成非常有用的工具,通过一些正确的...刺激...
是雷劈，所以刺激也行

2022-09-30 22:44 UTC, starxingchenc requested changes

2022-09-30 22:44 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest25.desc=你的目标变得更明确,你将需要砖块来完成你的第一个多方块构造.你认为104个砖块应该足够了.但是,你需要的方块有点特别,请确定你的制作方式是否正确!
multiblock structure
多方块结构

2022-09-30 22:44 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest25.desc=你的目标变得更明确,你将需要砖块来完成你的第一个多方块构造.你认为104个砖块应该足够了.但是,你需要的方块有点特别,请确定你的制作方式是否正确!
但是,你需要的方块有点特别
bricks
但是,你需要的砖块有点特别

2022-09-30 22:44 UTC, starxingchenc commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2035.desc=我好冷啊...想要正常使用这台机器,你需要给它持续供应极寒之凛冰.%n%n§3这台多方块机器可以在LuV阶段制造.
原文
gtnh.quest2035.desc=I'm so cold... You'll need a constant supply of Crysotheum to use it. You can also do recipes without cells now.%n%n§3This multi is LuV.

You can also do recipes without cells now. 未翻译

2022-10-01 12:43 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2035.desc=我好冷啊...想要正常使用这台机器,你需要给它持续供应极寒之凛冰.%n%n§3这台多方块机器可以在LuV阶段制造.
这个交过issue的，原文已经改了

2022-10-02 08:05 UTC, Kiwi233 requested changes

2022-10-02 08:05 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest710.desc=每个超容符文可以乘法叠加10％血之祭坛的容量.当增容符文超过14个之后,使用超容符文将更有效率.%n%%n每个宝珠符文可以增加4％的灵魂网络容量,你将在之后用到它的.
> %n%%n

这里百分号有问题

2022-10-02 08:05 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2044.desc=对于一个需要炼制§l荒唐§r数量材料的人来说,这台机器是完美的.  这个机器怪兽可以同时处理256个配方.%n%n玻璃等级(比如在NEI搜索"玻璃等级:HV")限制了这台机器的最高能源仓等级.%n%n你可以通过螺丝刀调整其主方块来设置电路板优先级.%n%n译者注:还可以用剪线钳右键主方块切换输入总线隔离.
启用独立输入总线功能

2022-10-02 08:05 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2085.desc=很难看出哪块树叶被授粉了.制作一副眼镜以获取更清晰的视图.
这个视图有点怪。。。

2022-10-02 08:05 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2188.desc=幻影蜂与幽灵蜂类似,但他们会复苏别的生物,比如恶魂、蜘蛛、爬行者、末影人甚至末影龙,它们的掉落物在附近的话就会被复活.由幽灵蜂和末影蜂杂交培育而来.
他们 它们
虽然不是啥大事

2022-10-02 08:05 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2249.desc=这只蜜蜂向你表现出纯粹的不屑,令人敬畏。必须在下界才能培育出来.没有适当防护就别在它周围走来走去,看起来它在发笑.由憎恶蜂和地狱蜂杂交培育而来.
唔 这个句号

2022-10-02 08:05 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2335.desc=巫媒(Taglock-Kit)用于收集其他玩家或生物的标记(Taglock),例如头发、指甲屑或血液,巫媒用于各种配方中,以在生物与巫术之间建立联系.%n%n想要收集巫媒,对着生物或者对着玩家使用过的床右键即可.在同一张床上重复右键,将循环收集用过该张床的每个玩家的巫媒.还可以在陷阱箱上收集打开箱子的玩家的巫媒,或在血玫瑰上收集走过它的玩家的巫媒.%n%n
这里的被动不能省略，或许可以改改更通顺一下
在各种配方中,巫师们通过巫媒,在生物与巫术之间建立联系.

2022-10-02 08:05 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2398.desc=你可能会注意到,当你在抽屉朝向的那面碰到抽屉墙时,会有一点点的延迟.如果不想有这种延迟的话,你可以制作此钥匙,让抽屉不在前部显示物品. 对抽屉管理器使用钥匙可以对整面抽屉墙生效.
> 当你在抽屉朝向的那面碰到抽屉墙时

当你在抽屉朝向的那面,并且碰到抽屉墙时

2022-10-02 11:07 UTC, Kiwi233 commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2674.desc=下一种材料是无尽催化剂. 无尽催化剂需要疯狂地压缩. 唯一可以做到的就是中子态素压缩机. 让我们合成一台.%n%n想要获得催化剂,你需要前往织女座B通过贫瘠矿获得粉. 然后将64个无尽催化剂粉压缩成一个无尽催化剂.%n%n当然你想试试无尽贪婪那个疯狂的手搓无尽催化剂的配方也没人拦着你,挑战自我吧 :P%n%n§3这台压缩机还可用于制造奇点,最终制成永恒奇点
译注里，鼠标中键还是滚轮？
中键可能更偏向与点击，滚轮则是滚动

2022-10-02 14:57 UTC, ChromicRedBrick commented on resources/minecraft/lang/zh_CN.lang
> +gtnh.quest2674.desc=下一种材料是无尽催化剂. 无尽催化剂需要疯狂地压缩. 唯一可以做到的就是中子态素压缩机. 让我们合成一台.%n%n想要获得催化剂,你需要前往织女座B通过贫瘠矿获得粉. 然后将64个无尽催化剂粉压缩成一个无尽催化剂.%n%n当然你想试试无尽贪婪那个疯狂的手搓无尽催化剂的配方也没人拦着你,挑战自我吧 :P%n%n§3这台压缩机还可用于制造奇点,最终制成永恒奇点
中键点击

2022-10-02 15:24 UTC, Kiwi233 approved these changes

2022-10-02 15:24 UTC, merged